export const EXIT_CODE_SUCCESS = 0
export const EXIT_CODE_GENERAL_ERROR = 1
export const EXIT_CODE_INVALID_CONFIGURATION = 2
export const EXIT_CODE_RULE_VIOLATION = 40

export type ExitCode =
	| typeof EXIT_CODE_SUCCESS
	| typeof EXIT_CODE_GENERAL_ERROR
	| typeof EXIT_CODE_INVALID_CONFIGURATION
	| typeof EXIT_CODE_RULE_VIOLATION
