export const EXIT_CODE_SUCCESS = 0
export const EXIT_CODE_GENERAL_ERROR = 1
export const EXIT_CODE_INVALID_CONFIGURATION = 2
export const EXIT_CODE_RULE_VIOLATION = 40

export const ALL_EXIT_CODES = [
	EXIT_CODE_SUCCESS,
	EXIT_CODE_GENERAL_ERROR,
	EXIT_CODE_INVALID_CONFIGURATION,
	EXIT_CODE_RULE_VIOLATION,
] as const

export type ExitCode = (typeof ALL_EXIT_CODES)[number]
